// <auto-generated />
using DotNetCore_Test.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DotNetCore_Test.Migrations
{
    [DbContext(typeof(TestContext))]
    [Migration("20201216030157_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DotNetCore_Test.Domain.Category", b =>
                {
                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryName");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryName = "Beverages",
                            Active = true,
                            Description = "Soft drinks"
                        },
                        new
                        {
                            CategoryName = "Dairy",
                            Active = true,
                            Description = "Cheeses"
                        },
                        new
                        {
                            CategoryName = "Condiments",
                            Active = true,
                            Description = "Sweet and savory sauces, relishes, spreads, and seasonings"
                        },
                        new
                        {
                            CategoryName = "Meat",
                            Active = true,
                            Description = "Prepared meats"
                        });
                });

            modelBuilder.Entity("DotNetCore_Test.Domain.Product", b =>
                {
                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<double>("Cost")
                        .HasColumnType("float");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductName");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductName = "Water",
                            Active = true,
                            Cost = 0.98999999999999999,
                            Description = "Fresh from the Mountains"
                        },
                        new
                        {
                            ProductName = "Milk",
                            Active = true,
                            Cost = 5.0,
                            Description = "Cow, Goat, Almond"
                        },
                        new
                        {
                            ProductName = "Cheese",
                            Active = true,
                            Cost = 8.0,
                            Description = "Cheddar, Pizza, Gouda"
                        },
                        new
                        {
                            ProductName = "Ketchup",
                            Active = true,
                            Cost = 10.99,
                            Description = "Goes with everything"
                        },
                        new
                        {
                            ProductName = "Steak",
                            Active = true,
                            Cost = 50.0,
                            Description = "Alberta Grade"
                        });
                });

            modelBuilder.Entity("DotNetCore_Test.Domain.ProductCategory", b =>
                {
                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CategoryName", "ProductName");

                    b.HasIndex("ProductName");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("DotNetCore_Test.Domain.ProductCategory", b =>
                {
                    b.HasOne("DotNetCore_Test.Domain.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DotNetCore_Test.Domain.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
